library:
  source-dirs: src
tests:
  AlloyHaskellTranslator-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - AlloyHaskellTranslator
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- tasty-hunit
- tasty
- base >= 4.7 && < 5
- mtl
name: AlloyHaskellTranslator
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/AlloyHaskellTranslator
license: BSD3
executables:
  AlloyHaskellTranslator-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AlloyHaskellTranslator
description: Please see the README on GitHub at <https://github.com/githubuser/AlloyHaskellTranslator#readme>
